### ISSUE TITLE
Files are not closed, and can't be deleted/released in filesystem (ubuntu)

### ISSUE THREAD

**Issue by megastef** [mingqi/tailF#9]
We see files, which can't be deleted, watched by tail-forever. 

1. create a file 
2. watch it with tail-forver
3. delete the file
4. check with  ```sudo lsof  | grep del``` (ubuntu) and the file is still listed and needs disk space.
5. Stop node process watching the file  and then the disk space gets released, the pid is not listed in ```sudo lsof  | grep del``` anymore. So the only workaround is to stop/start the process.

**Comment by megastef** [comment]
It is not clear to me if this line leads to closing the file: 
https://github.com/mingqi/tailF/blob/master/tail-forever.js#L271

There only two places where fs.close is called: https://github.com/mingqi/tailF/search?utf8=%E2%9C%93&q=fs.close - and I don't see how the push the task queue does finally call fs.close()

In addition in my tests sometimes "curr" argument of _watchFileEvent was "undefined". 
See https://github.com/mingqi/tailF/blob/master/tail-forever.js#L268

@mingqi could you please advise?

**Comment by mingqi** [comment]
@megastef this is a bug. I have fixed it and publish a new version v0.3.14, see commit  https://github.com/mingqi/tailF/commit/3eced76a4017d515135687c7c6ec09aac61f6a4f

**Comment by mingqi** [comment]
@megastef  Please use v0.3.15

**Comment by megastef** [comment]
Thanks for merging the PR!

One more comment, for people facing this problem even with latest tail-forever : 
The problem of not released disk space might still appear on Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-53-generic x86_64). We verified that the bug does not exist on Ubuntu Xenial (16.04 LTS) (GNU/Linux 4.5.7-std-3 x86_64 ) using the latest tail-forever version. 
Conclusion: A Kernel upgrade could help people to get the lost disk space released.
